config/routes.rb
Badrac::Application.routes.draw do

  resources :buscas  
  resources :articles
  resources :authors
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :keywords
 
  resources :journals do
    resources :editions
  end

  resources :editions do
    resources :articles
  end

  resources :articles do
    resources :keywords do
    get :autocomplete_keyword_kw_name, :on => :collection
  end
  end   

  resources :articles do
    resources :authors do
    get :autocomplete_author_fullname, :on => :collection
  end
  end 

  root to: 'buscas#index'

  match '/dica',      to: 'buscas#dica',          via: 'get'
  match '/sobre',     to: 'buscas#sobreprojeto',  via: 'get'
  match '/contato',   to: 'buscas#contato',       via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/tutorial',  to: 'journals#tutorial',    via: 'get'

  
    
end

app/models/edition.rb
class Edition < ActiveRecord::Base
	belongs_to :journal
	has_many :articles

	validates :e_name, presence: true, uniqueness: true
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
before_action :signed_in_user, only: [:index, :new, :edit, :create, 
                                      :update, :destroy]

  def index 
    @users = User.all   
    @journal = Journal.find(params[:journal_id])
    @editions = Edition.where(:journal_id => @journal.id).order('e_date DESC, e_name DESC')
  end

  def new  
    @journal = Journal.find(params[:journal_id])
    @edition = Edition.new
  end

  def edit  
    @journal = Journal.find (params[:journal_id])
    @edition = Edition.find(params[:id])
  end

  def create
    @journal = Journal.find(params[:journal_id])
    @edition = @journal.editions.build(edition_params)

    respond_to do |format|
      if @edition.save
        format.html { redirect_to journal_editions_path }
      else
        format.html { render action: 'new' }        
      end
    end
  end

  def update
    @edition = Edition.find(params[:id])

    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to edition_articles_path(@edition.id) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edition_params
      params.require(:edition).permit(:e_name, :e_date, :journal_id)
    end

end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/_form.html.erb
<%= form_for ([@journal, @edition]), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


  <div class="row">
    <div class="col-md-6">
      <%= f.text_field :e_name, :class => 'form-control input' , :placeholder=>"Nome da Edição"%>
    </div>
  </div>

<!-- Apenas o ano da edição. Serve como ordenação. -->
  <div class="row">
    <div class="col-md-2">
      <%= f.label :"Ano da Edição" %><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-1">
      <%= f.date_select :e_date, discard_day:true, discard_month:true, start_year: Date.today.year, end_year: 1990 %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <%= f.submit "Criar uma nova Edição",  :class => 'btn btn-primary btn-sm btn-block' %>
    </div>
  </div>

<% end %>

app/views/editions/edit.html.erb
<% provide(:title, 'Edição') %>

<h1>Editar Edição</h1>

<%= render 'form' %>

</br>

<div class="row">
   	<div class="col-md-3">
		<%= link_to 'Voltar', edition_articles_path(@edition.id),  :class => 'btn btn-default btn-sm' %>
	</div>
</div>

app/views/editions/index.html.erb
<% provide(:title, 'Edição') %>

<h1>Periódico</h1>

<table class="table table-striped table-bordered table-condensed" style="width: 100%">
  <tbody>     
    <tr>
      <td class="text-center" style="width: 12%">Periódico</td>
      <td><%= @journal.j_name %></td>
    <tr/>
  </tbody>
</table>
 
<div class="row">
  <div class="col-md-3">
<%= link_to 'Editar este periódico', edit_journal_path(@journal), :class => 'btn btn-primary btn-sm btn-block'%>
  </div>
  <div class="col-md-3">
    <% if current_user.admin? && !current_user?(@users) %>
      <%= link_to 'Remover este Periódico', @journal, :class => 'btn btn-danger btn-sm btn-block',  method: :delete, data: { confirm: 'Você tem certeza que deseja remover permanentemente este periódico e todas as edições e artigos a ele vinculadas?'} %>
    <% else %>
      <%= link_to 'Remover este Periódico', @journal, :class => 'btn btn-danger btn-sm btn-block disabled',  method: :delete, data: { confirm: 'Você tem certeza que deseja remover permanentemente este periódico e todas as edições e artigos a ele vinculadas?'} %>
    <% end %>
  </div>
  <div class="col-md-3">
<%= link_to 'Voltar', journals_path, :class => 'btn btn-default btn-sm'%>
  </div>
</div>

<br><br>

<h1>Edições deste periódico</h1>

<table class="table table-striped table-bordered table-condensed" style="width: 100%">
  <thead>
    <tr>
      <th class="text-center" style="width: 70%">Edição</th>
      <th class="text-center">Ano da Edição</th>
    </tr>
  </thead>

  <tbody>
    <% @editions.each do |edition| %>
      <tr>        
        <td><%= link_to edition.e_name, edition_articles_path(edition.id) %></td>
        <td><%= edition.e_date.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'Criar uma nova Edição', new_journal_edition_path(@journal), :class => 'btn btn-primary btn-sm btn-block'  %>
  </div>
</div>

app/views/editions/new.html.erb
<% provide(:title, 'Edição') %>

<h1>Crie uma nova Edição</h1>

<%= render 'form' %>

</br>

<div class="row">
   	<div class="col-md-3">
		<%= link_to 'Voltar', journal_editions_path,  :class => 'btn btn-default btn-sm' %>
	</div>
</div>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>E name:</strong>
  <%= @edition.e_name %>
</p>

<p>
  <strong>E date:</strong>
  <%= @edition.e_date %>
</p>



<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>