config/routes.rb
Badrac::Application.routes.draw do

  resources :buscas  
  resources :articles
  resources :authors
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :keywords
 
  resources :journals do
    resources :editions
  end

  resources :editions do
    resources :articles
  end

  resources :articles do
    resources :keywords do
    get :autocomplete_keyword_kw_name, :on => :collection
  end
  end   

  resources :articles do
    resources :authors do
    get :autocomplete_author_fullname, :on => :collection
  end
  end 

  root to: 'buscas#index'

  match '/dica',      to: 'buscas#dica',          via: 'get'
  match '/sobre',     to: 'buscas#sobreprojeto',  via: 'get'
  match '/contato',   to: 'buscas#contato',       via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/tutorial',  to: 'journals#tutorial',    via: 'get'

  
    
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :edition
  
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :keywords

  #validates :title, :abstract, presence: true
  validates :title, presence: true
  validates :url,
  			presence: true, 
  			format: { with: /http:|https:/, 
  			message: "Obrigatório o uso de http://www. ou https://www." }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :signed_in_user, only: [:index, :new, :edit, :create, 
                                      :update, :destroy]
  
  def index
    @users = User.all
    @edition = Edition.find(params[:edition_id])
    @articles = Article.where(:edition_id => @edition.id).order('id DESC')
  end

  def new  
    @edition = Edition.find(params[:edition_id])
    @article = Article.new
  end

  def edit  
    @edition = Edition.find (params[:edition_id])
    @article = Article.find(params[:id])
  end

  def create
    @edition = Edition.find(params[:edition_id])
    @article = @edition.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to edition_articles_path }

        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_keywords_path(@article.id, @article.edition_id) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @Article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :abstract, :url, :edition_id)
    end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for ([@edition, @article]), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


  <div class="row">
      <div class="col-md-6"> 
        <%= f.text_field :title, :class => 'form-control input', :placeholder=>"Título do Artigo" %>
      </div>
  </div>

  <div class="row">
      <div class="col-md-6"> 
        <%= f.text_field :abstract, :class => 'form-control input', :placeholder=>"Resumo" %>
      </div>
  </div>

  <div class="row">
      <div class="col-md-6"> 
        <%= f.text_field :url, :class => 'form-control input', :placeholder=>"Url - Use http(s)://www." %>
      </div>
  </div>

  <div class="row">
      <div class="col-md-3"> 
        <%= f.submit "Criar um novo Artigo", :class => 'btn btn-primary btn-sm btn-block'  %>
      </div>
  </div>
  
<% end %>

  

app/views/articles/edit.html.erb
<% provide(:title, 'Artigo') %>

<h1>Editar Artigos</h1>

<%= render 'form' %>
</br></br>
<div class="row">
  <div class="col-md-3">
	<%= link_to 'Voltar', article_keywords_path(@article.id, @article.edition_id),  :class => 'btn btn-default btn-sm' %>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Artigos') %>

<h1>Edição</h1>

<table class="table table-striped table-bordered table-condensed" style="width: 100%">
  <tbody>     
    <tr>
      <td class="text-center" style="width: 12%">Edição</td>
      <td><%= @edition.e_name %></td>
    <tr/>
  </tbody>
</table>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'Editar esta edição', edit_journal_edition_path(@edition.journal_id, @edition), :class => 'btn btn-primary btn-sm btn-block'%>
  </div>
  <div class="col-md-3">
    <% if current_user.admin? && !current_user?(@users) %>
      <%= link_to 'Remover esta Edição', @edition, :class => 'btn btn-danger btn-sm btn-block',  method: :delete, data: { confirm: 'Você tem certeza que deseja remover permanentemente esta edição e todos os artigos a ela vinculados?'} %>
    <% else %>
      <%= link_to 'Remover esta Edição', @edition, :class => 'btn btn-danger btn-sm btn-block disabled',  method: :delete, data: { confirm: 'Você tem certeza que deseja remover permanentemente esta edição e todos os artigos a ela vinculados?'} %>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Voltar', journal_editions_path(@edition.journal_id), :class => 'btn btn-default btn-sm' %>  </div>
</div>

<br><br>

<h1>Artigos desta edição</h1>

<% @articles.each do |article| %>
  <table class="table table-striped table-bordered table-condensed" style="width: 100%">
    <tbody> 
      <tr>
        <td class="text-center" style="width: 12%">Título</td>
        <td><%= link_to article.title, article_keywords_path(article.id, article.edition_id) %></td>
      <tr/>
      <tr>
        <td class="text-center" style="width: 12%">Resumo</td> 
        <td><%= article.abstract %></td>
      <tr/>  
      <tr>
        <td class="text-center" style="width: 12%">URL de Acesso</td>
        <td><%= article.url %></td>
      <tr/>         
    </tbody>
  </table>
<% end %> 

<br>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'Criar um novo Artigo', new_edition_article_path(@edition), :class => 'btn btn-primary btn-sm btn-block'  %>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'Artigos') %>

<h1>Criar um novo artigo</h1>

<%= render 'form' %>

</br></br>

<div class="row">
  <div class="col-md-3">
	<%= link_to 'Voltar', edition_articles_path(@edition),  :class => 'btn btn-default btn-sm' %>
  </div>
</div>