config/routes.rb
Badrac::Application.routes.draw do

  resources :buscas  
  resources :articles
  resources :authors
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :keywords
 
  resources :journals do
    resources :editions
  end

  resources :editions do
    resources :articles
  end

  resources :articles do
    resources :keywords do
    get :autocomplete_keyword_kw_name, :on => :collection
  end
  end   

  resources :articles do
    resources :authors do
    get :autocomplete_author_fullname, :on => :collection
  end
  end 

  root to: 'buscas#index'

  match '/dica',      to: 'buscas#dica',          via: 'get'
  match '/sobre',     to: 'buscas#sobreprojeto',  via: 'get'
  match '/contato',   to: 'buscas#contato',       via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/tutorial',  to: 'journals#tutorial',    via: 'get'

  
    
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_and_belongs_to_many :articles

    validates :kw_name, presence: true
    
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  autocomplete :keyword, :kw_name, :full => true

  before_action :set_keyword, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index, :new, :edit, :create, 
                                      :update, :destroy]

  def index
    #Quando faço - @edicao = Edicao.find (params[:edicao_id]) - nao tem id de edicao
    # entao coloquei um parametro a mais no link_to do INDEX de artigo (@edicao)
    # Fica como se fosse um paramentro em "format" 
    #<td><%= link_to 'INDEX', artigo_palavrachaves_path(artigo.id, @edicao.id) %></td>
    # url = palavrachave.format???????????
    # deu certo.
    
    @edition = Edition.find (params[:format])
    @article = Article.find (params[:article_id])
    @keywords =  Keyword.find_by_sql([
              "SELECT id, kw_name
              FROM    keywords,
                      articles_keywords
              WHERE   keywords.id = articles_keywords.keyword_id
                      AND articles_keywords.article_id = :id", {:id => params[:article_id]}])  
              
    @opas =  Keyword.find_by_sql([
              "SELECT id, fullname
              FROM    authors,
                      articles_authors
              WHERE   authors.id = articles_authors.author_id
                      AND articles_authors.article_id = :id", {:id => params[:article_id]}])
  end

  def show
  end

  def new
    @article = Article.find (params[:article_id])
    @keyword = Keyword.new
  end

  def edit
    @article = Article.find (params[:article_id])
    @keyword = Keyword.find(params[:id])
  end

  def create
      #Funciona perfeito. Mas insere repetidos.
      #@keyword = Keyword.new(keyword_params)
      #@article = Article.find (params[:article_id])
      #@keyword.articles << @article
      #FIM

      #Só insere em autores se não existir.
      #mas insere na junction table.
      @article = Article.find (params[:article_id])
      @keyword = Keyword.where(keyword_params).first_or_create  
      @keyword.articles << @article
    
    respond_to do |format|
      if @keyword.save
        format.html { redirect_to article_keywords_path(@article.id, @article.edition_id) }

        format.json { render action: 'show', status: :created, location: @keyword }
      else
        format.html { render action: 'new' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find (params[:article_id])
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to article_keywords_path(@article.id, @article.edition_id) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE HABTM
  def destroy
      article = Article.find(params[:article_id])
      keyword = article.keywords.find(params[:id])
     if keyword
        article.keywords.delete(keyword)
     end

     flash[:success] = "Palavra-chave Removida com sucesso."
     redirect_to article_keywords_path(article.id, article.edition_id)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def keyword_params
      params.require(:keyword).permit(:kw_name)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/edit.html.erb
<% provide(:title, 'Palavras-chave') %>

<h1>Edite ou Remova a Palavra-chave</h1>

<%= form_for ([@article, @keyword]), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
  	<div class="row">
      	<div class="col-md-6"> 
        	<%= f.autocomplete_field :kw_name, autocomplete_keyword_kw_name_article_keywords_path %>
      	</div>
   	</div>

</br> </br> </br> </br>

  	<div class="row">
      	<div class="col-md-3"> 
        	<%= f.submit "Editar Palavra-chave", :class => 'btn btn-primary btn-sm btn-block'  %>
      	</div>
  	  
		<div class="col-md-3" >  
  			<%= link_to "Remover Palavra-chave", article_keyword_path(@article.id, @keyword) , :class => 'btn btn-danger btn-sm btn-block', method: :delete,
                      data: { confirm: "Você tem certeza que deseja remover esta Palavra-chave??" } %>
    	</div>
    </div>
<% end %>

</br> </br>

<div class="row">
  <div class="col-md-3">
	<%= link_to 'Voltar', article_keywords_path(@article.id, @article.edition_id),  :class => 'btn btn-default btn-sm' %>
  </div> 
</div>

app/views/keywords/index.html.erb
<% provide(:title, 'Palavras-chave') %>

<h1>Edição</h1>

<table class="table table-striped table-bordered table-condensed" style="width: 100%">
  <tbody>     
    <tr>
      <td class="text-center" style="width: 12%">Edição</td>
      <td><%= @edition.e_name %></td>
    <tr/>
  </tbody>
</table>

<h1>Artigo</h1>

<tr>
<table class="table table-striped table-bordered table-condensed" style="width: 100%">
  <tbody>     
    <tr>
      <td class="text-center" style="width: 12%">Título</td>
      <td><%= @article.title %></td>
    <tr/>
    <tr>
      <td class="text-center" style="width: 12%">Resumo</td> 
      <td><%= @article.abstract %></td>
    <tr/>  
    <tr>
      <td class="text-center" style="width: 12%">URL de Acesso</td>
      <td><%= @article.url %></td>
    <tr/>     
  </tbody>
</table>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'Editar este artigo', edit_edition_article_path(@article.edition_id, @article), :class => 'btn btn-primary btn-sm btn-block'%>
  </div>
  <div class="col-md-3">
      <%= link_to 'Remover este Artigo', @article, :class => 'btn btn-danger btn-sm btn-block disabled',  method: :delete, data: { confirm: 'Você tem certeza que deseja remover permanentemente este artigo e todas as palavras-chave e autores a ele vinculados?'} %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Voltar', edition_articles_path(@edition), :class => 'btn btn-default btn-sm' %>  
  </div>
</div>

</br></br></br>

<div class="row">
  <div class="col-md-6">
    <table class="table table-striped table-bordered table-condensed" style="width: 100%">
      <thead>
        <tr>
          <th class="text-center">Palavra-chave</th>
          <th class="text-center">Editar/Remover</th> 
        </tr>
      </thead>

      <tbody>
        <% @keywords.each do |keyword| %>
          <tr>
            <td><%=keyword.kw_name%></td>
            <td class="text-center"><%=link_to 'Editar', edit_article_keyword_path(@article.id, keyword.id)%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <table class="table table-striped table-bordered table-condensed" style="width: 100%">
      <thead>
        <tr>
          <th class="text-center">Autores</th>
          <th class="text-center">Editar/Remover</th> 
        </tr>
      </thead>

      <tbody>
        <% @opas.each do |opa| %>
          <tr>
            <td><%= opa.fullname %></td>
            <td class="text-center"><%=link_to 'Editar', edit_article_author_path(@article, opa.id)%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
   
  <div class="col-md-3">
    <%= link_to 'Criar uma nova Palavras-chave', new_article_keyword_path(@article.id), :class => 'btn btn-primary btn-sm btn-block'%>
  </div>
<div class="col-md-3">
  </div>
  <div class="col-md-3">
    <%= link_to 'Criar um novo Autor', new_article_author_path(@article.id), :class => 'btn btn-primary btn-sm btn-block'%>
  </div>

  <div class="col-md-3">
  </div>
</div>

app/views/keywords/new.html.erb
<% provide(:title, 'Palavras-chave') %>

<h1>Crie uma nova Palavra-chave</h1>

<%= form_for ([@article, @keyword]), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
 
  	<div class="row">
      	<div class="col-md-6"> 
        	<%= f.autocomplete_field :kw_name, autocomplete_keyword_kw_name_article_keywords_path %>
      	</div>
   	</div>

</br> </br> </br> </br>

  	<div class="row">
      	<div class="col-md-3"> 
        	<%= f.submit "Criar Palavra-chave", :class => 'btn btn-primary btn btn-block'  %>
      	</div>
    </div>
<% end %>

</br> </br>

<div class="row">
  <div class="col-md-3">
	<%= link_to 'Voltar', article_keywords_path(@article.id, @article.edition_id),  :class => 'btn btn-default btn-sm' %>
  </div> 
</div>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kw name:</strong>
  <%= @keyword.kw_name %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>