config/routes.rb
Badrac::Application.routes.draw do

  resources :buscas  
  resources :articles
  resources :authors
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :keywords
 
  resources :journals do
    resources :editions
  end

  resources :editions do
    resources :articles
  end

  resources :articles do
    resources :keywords do
    get :autocomplete_keyword_kw_name, :on => :collection
  end
  end   

  resources :articles do
    resources :authors do
    get :autocomplete_author_fullname, :on => :collection
  end
  end 

  root to: 'buscas#index'

  match '/dica',      to: 'buscas#dica',          via: 'get'
  match '/sobre',     to: 'buscas#sobreprojeto',  via: 'get'
  match '/contato',   to: 'buscas#contato',       via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/tutorial',  to: 'journals#tutorial',    via: 'get'

  
    
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <!--#<a href="endereço lattes">Flavio Córdula</a>-->
    Base de Dados Referencial - Projeto de Mestrado PPGCI - UFPB | Copyright © 2013-2015 | v1.3.7
  </small>


  <nav>
    <ul>
      <li><%= link_to "Sobre este Projeto", '/sobre' %></li>
      <li><%= link_to "Contatos", '/contato' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Logo", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Busca de Periódicos", buscas_path%></li>
        </ul>
          <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Usuários", users_path %></li>
          </ul>
            <ul class="nav pull-right">
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Administrativo <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Tutorial Cadastro', '/tutorial' %></li>
                <li><%= link_to "Cadastro", journals_path%></li>
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>   
                  <% if current_user.admin? %> 
                    <%= link_to "Adicionar Usuário", signup_path %>
                  <%end%>  
                  <%= link_to "Sair", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Administrativo", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="btn btn-warning"><%= value %></div>
      <% end %>
      <%= yield %>
    </br>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>